<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logger\F1_19\**" />
    <EmbeddedResource Remove="Logger\F1_19\**" />
    <None Remove="Logger\F1_19\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.0.3" />
  </ItemGroup>

</Project>
